// <auto-generated />
namespace BankApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Wallets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wallets));
        
        string IMigrationMetadata.Id
        {
            get { return "202504060922241_Wallets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
